<a href="https://colab.research.google.com/github/gui98araujo/Amb_Git/blob/main/Case_Regressao_nao_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [24]:
#Loading the dataset of the case.

df = pd.read_excel('/content/house (1).xlsx')

In [25]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [26]:
df

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,Gd,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,TA,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,Gd,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,TA,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,Gd,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,TA,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,TA,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,Ex,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,TA,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,Gd,...,736,68,0,0,0,0,0,6,2008,147500

In [27]:
#Verifying the columns of the object type.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 40 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   OverallQual    1460 non-null   int64
 5   OverallCond    1460 non-null   int64
 6   YearBuilt      1460 non-null   int64
 7   YearRemodAdd   1460 non-null   int64
 8   MasVnrArea     1452 non-null   float64
 9   ExterQual      1460 non-null   object
 10  ExterCond      1460 non-null   object
 11  BsmtFinSF1     1460 non-null   int64
 12  BsmtFinSF2     1460 non-null   int64
 13  BsmtUnfSF      1460 non-null   int64
 14  TotalBsmtSF    1460 non-null   int64
 15  1stFlrSF       1460 non-null   int64
 16  2ndFlrSF       1460 non-null   int64
 17  LowQualFinSF   1460 non-null   int64
 18  GrLivArea      1460 non-null   int64
 19  BsmtFullBath   1460 non-null   int64
 20  BsmtHalfBath   1460 non-null   int64
 21  FullBath       1460 non-null   int64
 22  HalfBath       1460 non-null   int64
 23  BedroomAbvGr   1460 non-null   int64
 24  KitchenAbvGr   1460 non-null   int64
 25  TotRmsAbvGrd   1460 non-null   int64
 26  Fireplaces     1460 non-null   int64
 27  GarageYrBlt    1379 non-null   float64
 28  GarageCars     1460 non-null   int64
 29  GarageArea     1460 non-null   int64
 30  WoodDeckSF     1460 non-null   int64
 31  OpenPorchSF    1460 non-null   int64
 32  EnclosedPorch  1460 non-null   int64
 33  3SsnPorch      1460 non-null   int64
 34  ScreenPorch    1460 non-null   int64
 35  PoolArea       1460 non-null   int64
 36  MiscVal        1460 non-null   int64
 37  MoSold         1460 non-null   int64
 38  YrSold         1460 non-null   int64
 39  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(2)
memory usage: 456.4+ KB

In [28]:
#Removing the NaN values

df = df.dropna()

In [29]:
#Counting the values os the objects variables to identify how to proceed.
print(df.ExterQual.value_counts())
print(df.ExterCond.value_counts())

TA    670
Gd    398
Ex     46
Fa      7
Name: ExterQual, dtype: int64
TA    998
Gd    104
Fa     17
Ex      2
Name: ExterCond, dtype: int64

# Dummies #

In [30]:
# We can use the get dummies

df = pd.get_dummies(df)
df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,YrSold,SalePrice,ExterQual_Ex,ExterQual_Fa,ExterQual_Gd,ExterQual_TA,ExterCond_Ex,ExterCond_Fa,ExterCond_Gd,ExterCond_TA
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,2008,208500,0,0,1,0,0,0,0,1
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,2007,181500,0,0,0,1,0,0,0,1
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,2008,223500,0,0,1,0,0,0,0,1
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,2006,140000,0,0,0,1,0,0,0,1
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,2008,250000,0,0,1,0,0,0,0,1

# Treinando #

In [31]:
y = np.array(df['SalePrice'])

x =  df.drop("SalePrice", axis = 1)

In [32]:
x_list = list(x.columns)

In [33]:
x_list

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'ExterQual_Ex',
 'ExterQual_Fa',
 'ExterQual_Gd',
 'ExterQual_TA',
 'ExterCond_Ex',
 'ExterCond_Fa',
 'ExterCond_Gd',
 'ExterCond_TA']

In [34]:
x = np.array(x)

In [35]:
x

array([[1.000e+00, 6.000e+01, 6.500e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [2.000e+00, 2.000e+01, 8.000e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [3.000e+00, 6.000e+01, 6.800e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [1.458e+03, 7.000e+01, 6.600e+01, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [1.459e+03, 2.000e+01, 6.800e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.460e+03, 2.000e+01, 7.500e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [36]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.25, random_state=42)

In [37]:
from sklearn.datasets import make_moons
from sklearn import metrics
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor

In [38]:
# Training our base of train

rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
rf.fit(train_x, train_y)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [39]:
# Training the basetest
predction_rf= rf.predict(test_x)

error_rf = abs(predction_rf - test_y)

r_square = rf.score(x, y)

print('error', error_rf)
print('R^2', r_square)
print('MAE', metrics.mean_absolute_error(test_y, predction_rf))
print('MSE', metrics.mean_squared_error(test_y, predction_rf))

error [1.33059400e+03 7.50580000e+01 9.93519100e+03 2.96989800e+03
 1.83600800e+03 2.07841150e+04 2.29534690e+04 1.09469830e+04
 7.98892800e+03 2.76463800e+04 1.97216600e+04 1.10102238e+05
 2.37842310e+04 1.69819600e+04 7.21532200e+03 3.69311600e+03
 2.56878160e+04 9.81408700e+03 9.12073900e+03 9.17505200e+03
 4.57297900e+03 1.60995830e+04 8.07527500e+03 2.08626780e+04
 7.82234300e+03 1.74504300e+03 1.92421411e+05 1.02914400e+03
 4.74626000e+02 1.27857250e+04 1.90873200e+03 1.06972200e+04
 2.64568960e+04 2.16763330e+04 2.22075160e+04 7.39946600e+03
 1.80846030e+04 3.43753130e+04 2.23620940e+04 2.90872820e+04
 2.52374380e+04 4.04543110e+04 1.02615720e+04 1.03107000e+03
 3.26241350e+04 9.33137400e+03 1.60885000e+02 5.57548900e+03
 1.33478400e+03 4.43908570e+04 8.92068500e+03 1.57053003e+05
 7.69215300e+03 1.78455940e+04 2.24845510e+04 3.69502000e+04
 1.60554970e+04 3.42859600e+03 5.58361000e+02 3.53916000e+03
 1.37949900e+03 1.71148800e+03 2.88856900e+04 1.52423300e+03
 1.07749550e+04 2.99547200e+04 7.00742900e+03 2.70927510e+04
 7.32172100e+03 1.03405729e+05 7.80870000e+03 2.21833180e+04
 8.33588000e+03 3.98850900e+04 8.15012000e+02 1.73686300e+04
 1.23574590e+04 6.81635000e+02 7.69410800e+03 2.29864880e+04
 2.16125100e+04 1.89330020e+04 6.83772100e+03 1.26399510e+04
 9.02134000e+02 1.61193590e+04 5.93089600e+03 1.15201340e+04
 4.03955720e+04 6.17241700e+03 1.68256800e+04 3.07859200e+04
 7.67631000e+03 2.97107300e+03 5.88439400e+03 3.97668400e+03
 3.91042100e+03 1.79015380e+04 2.56094000e+02 3.64214340e+04
 5.04883000e+02 4.58840100e+03 2.69803600e+03 1.57411600e+03
 2.79053000e+02 2.99294910e+04 1.64885730e+04 3.39456900e+03
 1.42393870e+04 4.56329000e+02 1.61870020e+04 8.41939700e+03
 3.92692700e+03 3.77097200e+03 6.52838100e+03 3.35489920e+04
 2.74607660e+04 3.10781900e+03 2.75141750e+04 4.64685250e+04
 2.68910960e+04 1.04105630e+04 2.64519850e+04 1.16824310e+04
 5.43701240e+04 2.18307070e+04 9.59465600e+03 1.58173370e+04
 1.37844100e+04 2.66550680e+04 9.43236600e+03 1.23941340e+04
 1.83373580e+04 3.91400490e+04 1.47791590e+04 4.43519600e+03
 1.13125950e+04 3.98725800e+03 4.37704200e+03 8.11367100e+03
 5.74213300e+03 1.78619890e+04 9.25368500e+03 2.10978820e+04
 2.75175140e+04 4.09181900e+03 9.26235100e+03 8.39514500e+03
 3.49873800e+04 2.70054100e+03 1.67865880e+04 1.15796240e+04
 2.84869990e+04 4.89446280e+04 2.82931780e+04 2.74740300e+03
 3.34601000e+04 3.24683540e+04 1.81644386e+05 9.28972600e+03
 5.49845490e+04 9.11795600e+03 1.52051310e+04 3.04687220e+04
 3.05317740e+04 7.50705000e+04 9.10855200e+03 2.00390210e+04
 2.39732940e+04 1.55070900e+03 2.06230970e+04 4.30367000e+02
 1.51518300e+03 6.83938700e+03 1.24497620e+04 1.30431530e+04
 2.60123100e+03 2.38012020e+04 4.80600230e+04 2.34184870e+04
 1.59099510e+04 9.48252900e+03 3.98478330e+04 2.10801010e+04
 1.33458700e+03 3.38114530e+04 3.76758600e+03 2.49936460e+04
 4.54097400e+03 3.16140700e+03 2.99510460e+04 3.32960000e+01
 6.77050180e+04 1.54871100e+04 6.34584400e+03 8.44878300e+03
 2.29265430e+04 2.54140060e+04 5.62205600e+03 2.53583910e+04
 3.99422000e+02 1.41725800e+04 1.36217370e+04 3.86727270e+04
 1.18348340e+04 3.87802220e+04 5.07032930e+04 2.73138610e+04
 1.68402040e+04 2.16748880e+04 2.95867760e+04 1.43863380e+04
 2.16309980e+04 9.09078400e+03 1.29336430e+04 6.79139200e+03
 4.60674330e+04 1.36065692e+05 9.06792000e+03 2.49115750e+04
 1.18685700e+04 3.89223860e+04 4.32887430e+04 1.37698370e+04
 4.24660300e+03 2.33617470e+04 3.31096600e+04 3.32924100e+03
 2.09108690e+04 8.61589500e+03 4.05029560e+04 7.77096700e+03
 6.30891000e+03 1.85614710e+04 7.08112800e+03 5.62921500e+03
 2.17025360e+04 3.03471920e+04 3.01709550e+04 2.56707240e+04
 2.46215900e+03 6.14949800e+03 3.59683000e+02 8.76388900e+03
 6.89275300e+03 4.09456920e+04 9.10061400e+03 6.76229200e+03
 1.48922940e+04 3.98224400e+04 3.00865200e+03 6.90769100e+03
 2.58548850e+04 8.51867900e+03 1.65775870e+04 8.02811300e+03
 2.17865890e+04 4.61777800e+03 1.20955200e+04 1.44854200e+03
 1.34804640e+04 1.21294500e+04 8.11850000e+02 4.63546000e+03
 2.75135800e+03 1.01525000e+03 6.27380410e+04 5.79582100e+03
 6.56679550e+04 3.88374250e+04 2.12689590e+04 1.37743400e+03
 3.00074580e+04 4.02955430e+04 1.03272350e+04 2.08188400e+03
 1.54101120e+04 2.21578490e+04 3.17460000e+02 2.19237020e+04
 2.45559680e+04]
R^2 0.9485886719577706
MAE 19122.88696441281
MSE 937331048.1581936

In [45]:
ada = AdaBoostRegressor(n_estimators = 1000)
ada.fit(train_x, train_y)

ada_pred =  ada.predict(test_x)

In [46]:
error_ada = abs(ada_pred - test_y)

r_square = ada.score(x, y)

print('error', error_ada)
print('R^2', r_square)
print('MAE', metrics.mean_absolute_error(test_y, ada_pred))
print('MSE', metrics.mean_squared_error(test_y, ada_pred))

error [ 23332.44         3093.45614035   9915.27777778  25319.11864407
  40651.28205128   4485.63829787  15868.9112426   16020.25
  29165.57377049   6496.23134328  13144.44444444  92236.79831933
  12846.21666667  16467.815        4679.99056604   7220.15384615
  18963.03238866  27487.20930233   9401.6         35224.90710383
   9165.57377049   2419.80996885  52829.82474227  16889.97276265
  20869.32124352  49495.76373626 176825.11382114  10412.44094488
   1541.53846154   7249.18817204   1288.28571429  28291.02564103
   9725.99319728   9428.45714286  10658.04878049  18435.70285714
  15222.52873563  22382.2781457   34416.87804878  39378.09677419
  30162.22222222  20404.61353712  11171.36226415   6500.
  12715.34368071   9465.64827586  13493.40869565   7368.09243697
  16633.30980392  46587.14659686   8667.88636364 162984.1509434
   9995.08962264  11286.06849315   4982.18181818  35960.22941176
  23722.3622449    4399.52263374   5860.40512821  31644.50666667
  14382.36842105  22904.80571429   4900.          41167.97087379
   3286.19444444  12086.74698795  39583.33333333  27967.38095238
  16018.86538462 170516.61313869  13079.56281407  19427.35314685
  22484.64556962  39711.31828979   2042.70466321  17688.87155963
  10718.88950276  20491.35952381  21774.00680272  53561.46456693
  23116.16913319   1429.32638889  24645.07042254  12587.55905512
   4048.19047619  11507.40740741   8553.59393939   3334.82352941
  32923.40101523   4350.11312217  27056.63095238  48692.90666667
   2445.17717718  10368.19387755   1905.21875      3957.72307692
  46932.07364341  16918.28571429   3815.94155844  29240.39233038
  17368.09243697   2012.30252101    688.92397661  35642.17283951
  22663.89839572  37677.75714286   1740.86384977  12668.69230769
  17760.15873016  17500.45714286  32781.54726368  26255.39669421
   9243.05376344  28557.55        28889.59473684  58745.53174603
  53618.5625       8967.38095238  17311.72         5665.57377049
   1071.13924051   9179.99056604  22819.40277778  96151.36842105
  38348.65944272   9516.16393443  11648.83333333   3341.40753425
  15759.09090909  15713.26415094  10891.01111111  21645.00884956
  19327.22222222  36988.18859649   8547.53448276   3653.85955056
  14242.5625      14100.72576177  25070.61403509  31325.68965517
   4558.90776699  39308.69565217  14256.4516129   23266.79831933
  29311.12844037   4880.95238095  27054.84574468   6252.27777778
  13252.76439791   2757.49681529  14216.02390438   2526.23287671
  18495.38646288  45331.06273063  15468.79220779  14820.73819742
  31990.71428571  38875.25925926 198112.84199584   3924.74033149
  45524.59912854   9291.87417219  24052.12113402  19095.48314607
  22894.50666667  83302.87111111  13490.5462963    1395.74404762
  20914.47368421  17351.82105263  38254.           6436.04069767
  21274.00680272   6574.58064516  23285.98136646  20360.9127907
   7012.79069767  61667.34693878  32663.39285714  16311.20338983
   5398.42519685   2799.13855422  33777.82142857   2846.17297297
   5276.59574468  38531.25179856   6594.41520468  46838.18552036
  10012.06060606  50027.70621469  15137.00348432  18515.29357798
  79067.18534483   4700.78461538  25229.37142857   6295.98139535
   3089.94375     59142.17283951  18846.47887324   2804.53754941
   2039.65116279   6587.69230769  19322.04651163  24774.75
  23007.03205128  37715.54901961  66715.54901961  32658.48677249
  10937.97647059  14946.66666667  28582.34661355  32301.36764706
  25826.92307692  29571.54285714  32567.45614035   6691.0952381
  53137.6        162101.49888641   1714.01863354   4255.79856115
  17266.          50658.97883598 111990.69767442  37279.84615385
  31241.40753425  15206.25242718  68024.76373626  32786.13793103
  19286.80327869  48828.44        19493.37016575  14984.64556962
   5163.89839572  11151.92105263   7562.6626506    5971.42857143
  12313.7254902   72393.06907895  51038.1294964   73747.05882353
  14150.22818792  16249.43781095  19781.81818182   4382.91450777
   5973.60487805   2448.38421053  14467.64285714  33367.3655914
  46291.87417219  54508.52486188   6512.30252101   1725.96412556
  15631.99270073  37065.48314607  25625.93430657   1511.21978022
  34286.66666667  31954.07207207  29264.51434879   9057.55
   5132.72222222  23315.94155844  27475.33333333   9656.12903226
  26409.25819672  10111.91847826  96247.66887417  22963.57142857
 102276.03225806  24017.81818182  35120.61538462   3581.88641425
   5681.53846154  44860.76190476  37644.50666667  12974.5755814
   9208.98888889  13916.87804878   2670.03333333  27192.85714286
  21550.98039216]
R^2 0.8693121306150334
MAE 24635.34552056033
MSE 1377221908.4986963

In [47]:
gbr = GradientBoostingRegressor(n_estimators = 100)
gbr.fit(train_x, train_y)

gbr_pred =  gbr.predict(test_x)

In [48]:
error_gbr = abs(gbr_pred - test_y)

r_square = gbr.score(x, y)

print('error', error_gbr)
print('R^2', r_square)
print('MAE', metrics.mean_absolute_error(test_y, gbr_pred))
print('MSE', metrics.mean_squared_error(test_y, gbr_pred))

error [7.42006226e+03 2.21479763e+03 5.54475221e+03 7.34062040e+03
 1.08962649e+04 1.59386307e+04 7.95447597e+03 7.81184773e+03
 2.38245060e+04 1.86655484e+04 1.10297415e+04 7.12265631e+04
 2.44471938e+04 2.11588733e+04 1.87008349e+03 3.32872373e+03
 2.27600833e+04 1.63454550e+04 2.10821162e+03 8.20304533e+03
 2.23040290e+03 8.91283335e+03 1.80340092e+04 1.55488149e+04
 1.49610589e+04 1.75357711e+04 1.64309982e+05 2.40509111e+04
 5.85762887e+03 1.14668153e+04 2.25424341e+03 4.19585739e+03
 1.07200528e+04 3.05855236e+04 3.15072773e+04 1.85277051e+04
 9.77670411e+03 1.99780942e+04 2.21600716e+04 2.27644758e+04
 2.42574931e+04 3.84902503e+04 1.54591132e+04 6.70356325e+03
 4.39895641e+04 2.77038526e+04 7.26979458e+03 9.42381758e+03
 4.22164067e+03 2.45722392e+04 6.41554636e+03 1.60544956e+05
 1.31314602e+04 1.40912615e+04 1.08068969e+04 4.43897228e+04
 2.71538421e+04 5.60108183e+03 9.10082064e+02 3.34603279e+02
 4.67517004e+03 2.97042060e+03 2.01690280e+04 6.56381476e+03
 5.43458585e+03 2.20153322e+04 8.64701992e+02 1.54053845e+04
 6.64958897e+03 8.83747422e+04 1.99534717e+03 1.64767237e+04
 7.29686493e+03 1.79807553e+04 7.99037195e+03 9.93285149e+03
 3.78122205e+01 1.50520294e+04 1.50589753e+04 1.32776539e+04
 3.23859623e+04 2.38123576e+04 2.64097824e+04 1.81778185e+04
 9.11208619e+03 2.30905311e+04 1.06725037e+04 1.72505088e+04
 2.46610935e+04 6.19576195e+03 1.41700752e+04 2.56211016e+04
 1.37817397e+04 2.80484875e+04 5.87090804e+03 7.63529461e+03
 1.31296733e+04 1.73813053e+04 5.33756210e+02 2.97644321e+04
 7.77152542e+02 6.91343517e+03 3.57191944e+03 8.45797855e+02
 1.60955041e+04 2.25630256e+04 4.93487633e+03 2.33259641e+03
 2.30401955e+04 8.47160827e+03 1.69184278e+04 1.41270411e+04
 4.15400511e+03 1.68622945e+03 2.38364478e+04 3.18044251e+04
 3.35885443e+04 1.35529068e+03 1.88929981e+04 2.41099434e+04
 4.12852121e+04 2.73088074e+03 2.31547406e+04 4.15217661e+04
 3.49532469e+04 3.29175282e+03 7.68234199e+02 4.25797577e+03
 5.52154962e+03 1.75590588e+04 8.88560745e+03 8.73248337e+03
 1.27771411e+04 2.98469944e+04 2.23019177e+04 8.24384651e+03
 8.43197362e+03 8.16021415e+03 2.39012705e+03 1.06410976e+04
 1.73079962e+04 5.12243265e+04 7.30690185e+03 3.56262391e+04
 1.94849444e+04 6.68088323e+03 7.18774577e+03 2.21775482e+04
 1.23318960e+04 7.50888296e+03 8.90922836e+03 7.45977644e+03
 2.20960710e+04 4.57356211e+04 3.41495118e+04 1.89266699e+04
 3.65155643e+04 2.89022027e+04 1.98860438e+05 6.61925542e+03
 5.20482498e+04 1.00028790e+04 9.73092767e+03 2.19153042e+04
 3.37144254e+04 7.25133737e+04 1.90555435e+04 1.16393992e+04
 1.21441476e+04 3.98415945e+03 1.79205657e+04 7.61229594e+02
 3.34970320e+03 9.18447801e+03 7.27641473e+03 1.36679659e+04
 5.93253985e+03 1.53738107e+04 4.08741890e+04 2.88226070e+04
 7.81181763e+03 6.60154584e+03 1.51045899e+04 1.17643936e+04
 3.91614419e+02 3.24810490e+04 1.87510441e+03 1.23443251e+04
 6.16074559e+03 5.20301125e+03 3.49980925e+04 8.65022044e+02
 3.48416540e+04 1.04960568e+04 1.00939110e+04 2.05591920e+04
 1.25496686e+04 2.22974195e+04 6.63187708e+02 2.21803626e+04
 1.00308730e+03 1.05105482e+04 1.72432299e+04 3.67974982e+04
 1.51115987e+04 1.70552135e+04 4.79800077e+04 3.74890796e+04
 2.51405887e+04 1.93387240e+04 1.41268378e+03 1.24031523e+04
 2.58758153e+04 1.32478046e+04 2.70888607e+04 4.87078590e+03
 1.88329367e+04 1.35305876e+05 1.24555735e+04 1.00558798e+04
 2.39225835e+04 2.22393370e+04 5.16855539e+04 2.67650637e+04
 9.51159830e+03 1.35722982e+04 4.13910644e+04 5.66693983e+03
 1.38627331e+04 7.63126601e+02 4.26342850e+04 4.53959969e+03
 5.15977557e+03 3.00964501e+04 3.05375614e+03 6.08541648e+03
 3.51650149e+04 3.54114280e+04 5.18660205e+04 2.07322040e+04
 7.09648898e+02 7.28420927e+03 2.36826290e+04 1.08274122e+04
 8.97249731e+03 6.14426430e+04 1.08693470e+03 1.00254874e+04
 2.44363663e+03 3.16391634e+04 1.34134618e+04 3.42237536e+03
 2.23711024e+04 9.80431721e+03 1.43807130e+04 9.14978029e+03
 6.46322794e+02 1.17960459e+04 9.29323204e+03 7.70465225e+03
 1.18696012e+04 8.68612364e+03 7.70914333e+03 3.16089864e+03
 2.45244847e+03 4.44331963e+03 5.09319506e+04 1.00854970e+04
 4.83554780e+04 3.33237054e+04 1.62313510e+04 1.56403221e+04
 3.50734859e+04 8.24438831e+03 1.02086717e+03 1.62367704e+02
 1.93671217e+04 5.02547426e+03 3.09586598e+03 2.98996545e+04
 2.34732760e+04]
R^2 0.9488992574857327
MAE 18499.072215808927
MSE 850257722.2944025

In [49]:
# Get numerical feature importances
importances = list(rf.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(x_list, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: OverallQual          Importance: 0.61
Variable: GrLivArea            Importance: 0.09
Variable: BsmtFinSF1           Importance: 0.03
Variable: TotalBsmtSF          Importance: 0.03
Variable: 2ndFlrSF             Importance: 0.03
Variable: LotArea              Importance: 0.02
Variable: 1stFlrSF             Importance: 0.02
Variable: GarageCars           Importance: 0.02
Variable: LotFrontage          Importance: 0.01
Variable: YearBuilt            Importance: 0.01
Variable: YearRemodAdd         Importance: 0.01
Variable: MasVnrArea           Importance: 0.01
Variable: BsmtUnfSF            Importance: 0.01
Variable: FullBath             Importance: 0.01
Variable: TotRmsAbvGrd         Importance: 0.01
Variable: GarageYrBlt          Importance: 0.01
Variable: GarageArea           Importance: 0.01
Variable: OpenPorchSF          Importance: 0.01
Variable: Id                   Importance: 0.0
Variable: MSSubClass           Importance: 0.0
Variable: OverallCond          Importance: 0.0
Variable: BsmtFinSF2           Importance: 0.0
Variable: LowQualFinSF         Importance: 0.0
Variable: BsmtFullBath         Importance: 0.0
Variable: BsmtHalfBath         Importance: 0.0
Variable: HalfBath             Importance: 0.0
Variable: BedroomAbvGr         Importance: 0.0
Variable: KitchenAbvGr         Importance: 0.0
Variable: Fireplaces           Importance: 0.0
Variable: WoodDeckSF           Importance: 0.0
Variable: EnclosedPorch        Importance: 0.0
Variable: 3SsnPorch            Importance: 0.0
Variable: ScreenPorch          Importance: 0.0
Variable: PoolArea             Importance: 0.0
Variable: MiscVal              Importance: 0.0
Variable: MoSold               Importance: 0.0
Variable: YrSold               Importance: 0.0
Variable: ExterQual_Ex         Importance: 0.0
Variable: ExterQual_Fa         Importance: 0.0
Variable: ExterQual_Gd         Importance: 0.0
Variable: ExterQual_TA         Importance: 0.0
Variable: ExterCond_Ex         Importance: 0.0
Variable: ExterCond_Fa         Importance: 0.0
Variable: ExterCond_Gd         Importance: 0.0
Variable: ExterCond_TA         Importance: 0.0

In [50]:
# Get numerical feature importances
importances = list(ada.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(x_list, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: OverallQual          Importance: 0.21
Variable: 2ndFlrSF             Importance: 0.18
Variable: GrLivArea            Importance: 0.09
Variable: OpenPorchSF          Importance: 0.07
Variable: LotArea              Importance: 0.06
Variable: GarageCars           Importance: 0.05
Variable: LotFrontage          Importance: 0.03
Variable: YearBuilt            Importance: 0.03
Variable: FullBath             Importance: 0.03
Variable: WoodDeckSF           Importance: 0.03
Variable: ScreenPorch          Importance: 0.03
Variable: PoolArea             Importance: 0.03
Variable: Id                   Importance: 0.02
Variable: BsmtFinSF1           Importance: 0.02
Variable: MoSold               Importance: 0.02
Variable: YearRemodAdd         Importance: 0.01
Variable: TotalBsmtSF          Importance: 0.01
Variable: 1stFlrSF             Importance: 0.01
Variable: BedroomAbvGr         Importance: 0.01
Variable: GarageYrBlt          Importance: 0.01
Variable: GarageArea           Importance: 0.01
Variable: MSSubClass           Importance: 0.0
Variable: OverallCond          Importance: 0.0
Variable: MasVnrArea           Importance: 0.0
Variable: BsmtFinSF2           Importance: 0.0
Variable: BsmtUnfSF            Importance: 0.0
Variable: LowQualFinSF         Importance: 0.0
Variable: BsmtFullBath         Importance: 0.0
Variable: BsmtHalfBath         Importance: 0.0
Variable: HalfBath             Importance: 0.0
Variable: KitchenAbvGr         Importance: 0.0
Variable: TotRmsAbvGrd         Importance: 0.0
Variable: Fireplaces           Importance: 0.0
Variable: EnclosedPorch        Importance: 0.0
Variable: 3SsnPorch            Importance: 0.0
Variable: MiscVal              Importance: 0.0
Variable: YrSold               Importance: 0.0
Variable: ExterQual_Ex         Importance: 0.0
Variable: ExterQual_Fa         Importance: 0.0
Variable: ExterQual_Gd         Importance: 0.0
Variable: ExterQual_TA         Importance: 0.0
Variable: ExterCond_Ex         Importance: 0.0
Variable: ExterCond_Fa         Importance: 0.0
Variable: ExterCond_Gd         Importance: 0.0
Variable: ExterCond_TA         Importance: 0.0

In [51]:
# Get numerical feature importances
importances = list(gbr.feature_importances_)
# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(x_list, importances)]
# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: OverallQual          Importance: 0.54
Variable: GrLivArea            Importance: 0.1
Variable: TotalBsmtSF          Importance: 0.07
Variable: 2ndFlrSF             Importance: 0.05
Variable: BsmtFinSF1           Importance: 0.04
Variable: GarageCars           Importance: 0.04
Variable: LotArea              Importance: 0.02
Variable: YearBuilt            Importance: 0.02
Variable: YearRemodAdd         Importance: 0.02
Variable: 1stFlrSF             Importance: 0.02
Variable: FullBath             Importance: 0.02
Variable: LotFrontage          Importance: 0.01
Variable: OverallCond          Importance: 0.01
Variable: Fireplaces           Importance: 0.01
Variable: GarageArea           Importance: 0.01
Variable: OpenPorchSF          Importance: 0.01
Variable: Id                   Importance: 0.0
Variable: MSSubClass           Importance: 0.0
Variable: MasVnrArea           Importance: 0.0
Variable: BsmtFinSF2           Importance: 0.0
Variable: BsmtUnfSF            Importance: 0.0
Variable: LowQualFinSF         Importance: 0.0
Variable: BsmtFullBath         Importance: 0.0
Variable: BsmtHalfBath         Importance: 0.0
Variable: HalfBath             Importance: 0.0
Variable: BedroomAbvGr         Importance: 0.0
Variable: KitchenAbvGr         Importance: 0.0
Variable: TotRmsAbvGrd         Importance: 0.0
Variable: GarageYrBlt          Importance: 0.0
Variable: WoodDeckSF           Importance: 0.0
Variable: EnclosedPorch        Importance: 0.0
Variable: 3SsnPorch            Importance: 0.0
Variable: ScreenPorch          Importance: 0.0
Variable: PoolArea             Importance: 0.0
Variable: MiscVal              Importance: 0.0
Variable: MoSold               Importance: 0.0
Variable: YrSold               Importance: 0.0
Variable: ExterQual_Ex         Importance: 0.0
Variable: ExterQual_Fa         Importance: 0.0
Variable: ExterQual_Gd         Importance: 0.0
Variable: ExterQual_TA         Importance: 0.0
Variable: ExterCond_Ex         Importance: 0.0
Variable: ExterCond_Fa         Importance: 0.0
Variable: ExterCond_Gd         Importance: 0.0
Variable: ExterCond_TA         Importance: 0.0