<a href="https://colab.research.google.com/github/gui98araujo/Amb_Git/blob/main/Variavel_Dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
limite=pd.read_excel('/content/CÃ³pia de Limite_Credito.xlsx')
limite.head()

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,LimitedoChequeEspecial,Escolaridade
0,70,10736,5214,400,500,Fundamental_Medio
1,68,5000,5000,380,600,Fundamental_Medio
2,44,5800,5800,500,800,Fundamental_Medio
3,72,4300,4300,2000,1000,Fundamental_Medio
4,75,4400,4400,3000,1000,Fundamental_Medio

In [7]:
#O modelo de regressÃ£o nÃ£o lÃª variÃ¡vel categÃ³rica
limite=pd.get_dummies(limite, prefix=['escolaridade'])
limite.head(10)

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,LimitedoChequeEspecial,escolaridade_Fundamental_Medio,escolaridade_Superior_Pos
0,70,10736,5214,400,500,1,0
1,68,5000,5000,380,600,1,0
2,44,5800,5800,500,800,1,0
3,72,4300,4300,2000,1000,1,0
4,75,4400,4400,3000,1000,1,0
5,35,5000,5000,1000,1000,1,0
6,80,8100,8100,3500,1000,1,0
7,66,4800,4800,440,1500,1,0
8,39,6320,6320,1550,1640,1,0
9,47,5000,5000,2000,1700,1,0

In [8]:
limite.corr()

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,LimitedoChequeEspecial,escolaridade_Fundamental_Medio,escolaridade_Superior_Pos
Idade,1.000000,0.066396,0.063227,0.064149,0.075883,-0.110892,0.110892
RendimentoTotal,0.066396,1.000000,0.960551,0.031041,0.858120,-0.396191,0.396191
Salario,0.063227,0.960551,1.000000,0.081792,0.888839,-0.475479,0.475479
LimitedeCreditoImediato,0.064149,0.031041,0.081792,1.000000,0.226990,-0.259433,0.259433
LimitedoChequeEspecial,0.075883,0.858120,0.888839,0.226990,1.000000,-0.598310,0.598310
escolaridade_Fundamental_Medio,-0.110892,-0.396191,-0.475479,-0.259433,-0.598310,1.000000,-1.000000
escolaridade_Superior_Pos,0.110892,0.396191,0.475479,0.259433,0.598310,-1.000000,1.000000

In [9]:
import statsmodels.formula.api as smf

In [10]:
function='LimitedoChequeEspecial~Idade+RendimentoTotal+Salario	+  LimitedeCreditoImediato+ escolaridade_Fundamental_Medio+ escolaridade_Superior_Pos'

In [12]:
model=smf.ols(formula=function,data=limite).fit()

In [13]:
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.848
Model:                                OLS   Adj. R-squared:                  0.830
Method:                     Least Squares   F-statistic:                     46.89
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           4.07e-16
Time:                            14:01:41   Log-Likelihood:                -441.00
No. Observations:                      48   AIC:                             894.0
Df Residuals:                          42   BIC:                             905.2
Df Model:                               5
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -509.4948   1248.421     -0.408      0.685   -3028.910    2009.920
Idade                             -2.7480     24.707     -0.111      0.912     -52.608      47.112
RendimentoTotal                    0.1461      0.109      1.338      0.188      -0.074       0.366
Salario                            0.3201      0.154      2.079      0.044       0.009       0.631
LimitedeCreditoImediato            0.7979      0.411      1.943      0.059      -0.031       1.627
escolaridade_Fundamental_Medio -1611.3283    619.903     -2.599      0.013   -2862.343    -360.313
escolaridade_Superior_Pos       1101.8335    899.444      1.225      0.227    -713.319    2916.986
==============================================================================
Omnibus:                        3.246   Durbin-Watson:                   1.979
Prob(Omnibus):                  0.197   Jarque-Bera (JB):                2.813
Skew:                           0.031   Prob(JB):                        0.245
Kurtosis:                       4.184   Cond. No.                     3.32e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.18e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [14]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario	+  LimitedeCreditoImediato+ escolaridade_Fundamental_Medio+ escolaridade_Superior_Pos'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.848
Model:                                OLS   Adj. R-squared:                  0.834
Method:                     Least Squares   F-statistic:                     59.99
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           4.92e-17
Time:                            14:02:36   Log-Likelihood:                -441.01
No. Observations:                      48   AIC:                             892.0
Df Residuals:                          43   BIC:                             901.4
Df Model:                               4
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                       -619.3788    754.395     -0.821      0.416   -2140.761     902.003
RendimentoTotal                    0.1455      0.108      1.350      0.184      -0.072       0.363
Salario                            0.3208      0.152      2.110      0.041       0.014       0.627
LimitedeCreditoImediato            0.7960      0.406      1.962      0.056      -0.022       1.614
escolaridade_Fundamental_Medio -1661.7862    417.576     -3.980      0.000   -2503.908    -819.664
escolaridade_Superior_Pos       1042.4074    715.195      1.458      0.152    -399.921    2484.736
==============================================================================
Omnibus:                        3.276   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.194   Jarque-Bera (JB):                2.867
Skew:                           0.016   Prob(JB):                        0.238
Kurtosis:                       4.197   Cond. No.                     2.31e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.51e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [15]:
#Subtraimos 1 na formula para remover o intercept
function='LimitedoChequeEspecial~RendimentoTotal+Salario	+  LimitedeCreditoImediato+ escolaridade_Fundamental_Medio+ escolaridade_Superior_Pos-1'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.848
Model:                                OLS   Adj. R-squared:                  0.834
Method:                     Least Squares   F-statistic:                     59.99
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           4.92e-17
Time:                            14:04:18   Log-Likelihood:                -441.01
No. Observations:                      48   AIC:                             892.0
Df Residuals:                          43   BIC:                             901.4
Df Model:                               4
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
RendimentoTotal                    0.1455      0.108      1.350      0.184      -0.072       0.363
Salario                            0.3208      0.152      2.110      0.041       0.014       0.627
LimitedeCreditoImediato            0.7960      0.406      1.962      0.056      -0.022       1.614
escolaridade_Fundamental_Medio -2281.1650    987.653     -2.310      0.026   -4272.957    -289.373
escolaridade_Superior_Pos        423.0286   1409.561      0.300      0.766   -2419.621    3265.678
==============================================================================
Omnibus:                        3.276   Durbin-Watson:                   1.991
Prob(Omnibus):                  0.194   Jarque-Bera (JB):                2.867
Skew:                           0.016   Prob(JB):                        0.238
Kurtosis:                       4.197   Cond. No.                     1.01e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.01e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [16]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario	+  LimitedeCreditoImediato+ escolaridade_Fundamental_Medio-1'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                                   OLS Regression Results
===========================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared (uncentered):                   0.918
Model:                                OLS   Adj. R-squared (uncentered):              0.911
Method:                     Least Squares   F-statistic:                              123.2
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):                    2.66e-23
Time:                            14:05:14   Log-Likelihood:                         -441.06
No. Observations:                      48   AIC:                                      890.1
Df Residuals:                          44   BIC:                                      897.6
Df Model:                               4
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
RendimentoTotal                    0.1404      0.105      1.333      0.189      -0.072       0.353
Salario                            0.3350      0.143      2.342      0.024       0.047       0.623
LimitedeCreditoImediato            0.8827      0.282      3.132      0.003       0.315       1.451
escolaridade_Fundamental_Medio -2511.0773    616.877     -4.071      0.000   -3754.312   -1267.843
==============================================================================
Omnibus:                        3.142   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.208   Jarque-Bera (JB):                2.657
Skew:                          -0.017   Prob(JB):                        0.265
Kurtosis:                       4.152   Cond. No.                     3.87e+04
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 3.87e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [17]:
function='LimitedoChequeEspecial~Salario	+  LimitedeCreditoImediato+ escolaridade_Fundamental_Medio-1'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                                   OLS Regression Results
===========================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared (uncentered):                   0.915
Model:                                OLS   Adj. R-squared (uncentered):              0.909
Method:                     Least Squares   F-statistic:                              160.9
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):                    4.57e-24
Time:                            14:05:36   Log-Likelihood:                         -442.01
No. Observations:                      48   AIC:                                      890.0
Df Residuals:                          45   BIC:                                      895.6
Df Model:                               3
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Salario                            0.5192      0.037     14.031      0.000       0.445       0.594
LimitedeCreditoImediato            0.7588      0.268      2.828      0.007       0.218       1.299
escolaridade_Fundamental_Medio -2390.0248    615.400     -3.884      0.000   -3629.504   -1150.545
==============================================================================
Omnibus:                        2.678   Durbin-Watson:                   1.961
Prob(Omnibus):                  0.262   Jarque-Bera (JB):                1.767
Skew:                           0.238   Prob(JB):                        0.413
Kurtosis:                       3.811   Cond. No.                     2.41e+04
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.41e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [18]:
limite=pd.read_excel('/content/Cââpia de Limite_Credito_Dummy.xlsx')
limite.head()

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,Escolaridade,GÃªnero,RegiÃ£o,LimitedoChequeEspecial
0,70,10736,5214,400,Fundamental_Medio,RJ,F,500
1,68,5000,5000,380,Fundamental_Medio,RJ,F,600
2,44,5800,5800,500,Fundamental_Medio,RJ,F,800
3,72,4300,4300,2000,Fundamental_Medio,RJ,F,1000
4,75,4400,4400,3000,Fundamental_Medio,RJ,F,1000

In [19]:
limite=pd.get_dummies(limite)

In [20]:
limite.head()

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,LimitedoChequeEspecial,Escolaridade_Fundamental_Medio,Escolaridade_Superior_Pos,GÃªnero_RJ,GÃªnero_SP,RegiÃ£o_F,RegiÃ£o_M
0,70,10736,5214,400,500,1,0,1,0,1,0
1,68,5000,5000,380,600,1,0,1,0,1,0
2,44,5800,5800,500,800,1,0,1,0,1,0
3,72,4300,4300,2000,1000,1,0,1,0,1,0
4,75,4400,4400,3000,1000,1,0,1,0,1,0

In [21]:
limite.corr()

,Idade,RendimentoTotal,Salario,LimitedeCreditoImediato,LimitedoChequeEspecial,Escolaridade_Fundamental_Medio,Escolaridade_Superior_Pos,GÃªnero_RJ,GÃªnero_SP,RegiÃ£o_F,RegiÃ£o_M
Idade,1.000000,0.239445,0.213186,0.057183,0.228117,-0.150088,0.150088,-0.196052,0.196052,-0.121217,0.121217
RendimentoTotal,0.239445,1.000000,0.960551,0.031041,0.858120,-0.396191,0.396191,-0.177798,0.177798,-0.406241,0.406241
Salario,0.213186,0.960551,1.000000,0.081792,0.888839,-0.475479,0.475479,-0.242621,0.242621,-0.424335,0.424335
LimitedeCreditoImediato,0.057183,0.031041,0.081792,1.000000,0.226990,-0.259433,0.259433,-0.001145,0.001145,-0.473326,0.473326
LimitedoChequeEspecial,0.228117,0.858120,0.888839,0.226990,1.000000,-0.598310,0.598310,-0.312566,0.312566,-0.591779,0.591779
Escolaridade_Fundamental_Medio,-0.150088,-0.396191,-0.475479,-0.259433,-0.598310,1.000000,-1.000000,0.237508,-0.237508,0.602464,-0.602464
Escolaridade_Superior_Pos,0.150088,0.396191,0.475479,0.259433,0.598310,-1.000000,1.000000,-0.237508,0.237508,-0.602464,0.602464
GÃªnero_RJ,-0.196052,-0.177798,-0.242621,-0.001145,-0.312566,0.237508,-0.237508,1.000000,-1.000000,-0.167248,0.167248
GÃªnero_SP,0.196052,0.177798,0.242621,0.001145,0.312566,-0.237508,0.237508,-1.000000,1.000000,0.167248,-0.167248
RegiÃ£o_F,-0.121217,-0.406241,-0.424335,-0.473326,-0.591779,0.602464,-0.602464,-0.167248,0.167248,1.000000,-1.000000
RegiÃ£o_M,0.121217,0.406241,0.424335,0.473326,0.591779,-0.602464,0.602464,0.167248,-0.167248,-1.000000,1.000000

In [24]:
function='LimitedoChequeEspecial~Idade+RendimentoTotal+Salario	+  LimitedeCreditoImediato+ Escolaridade_Fundamental_Medio+ Escolaridade_Superior_Pos+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.886
Model:                                OLS   Adj. R-squared:                  0.865
Method:                     Least Squares   F-statistic:                     44.20
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           7.44e-17
Time:                            14:23:45   Log-Likelihood:                -434.21
No. Observations:                      48   AIC:                             884.4
Df Residuals:                          40   BIC:                             899.4
Df Model:                               7
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                        398.6632    705.403      0.565      0.575   -1027.009    1824.335
Idade                             -4.9864     22.665     -0.220      0.827     -50.793      40.820
RendimentoTotal                    0.1354      0.101      1.336      0.189      -0.069       0.340
Salario                            0.2799      0.142      1.977      0.055      -0.006       0.566
LimitedeCreditoImediato            0.2439      0.414      0.589      0.559      -0.593       1.081
Escolaridade_Fundamental_Medio  -223.4354    572.451     -0.390      0.698   -1380.402     933.531
Escolaridade_Superior_Pos        622.0986    629.942      0.988      0.329    -651.062    1895.259
GÃªnero_RJ                       -967.2953    445.962     -2.169      0.036   -1868.619     -65.972
GÃªnero_SP                       1365.9585    598.088      2.284      0.028     157.177    2574.740
RegiÃ£o_F                       -1456.4227    533.381     -2.731      0.009   -2534.425    -378.420
RegiÃ£o_M                        1855.0859    718.221      2.583      0.014     403.507    3306.665
==============================================================================
Omnibus:                       15.742   Durbin-Watson:                   1.724
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.550
Skew:                          -0.679   Prob(JB):                     9.50e-10
Kurtosis:                       7.351   Cond. No.                     5.34e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.44e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [25]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario	+  LimitedeCreditoImediato+ Escolaridade_Fundamental_Medio+ Escolaridade_Superior_Pos+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.885
Model:                                OLS   Adj. R-squared:                  0.869
Method:                     Least Squares   F-statistic:                     52.78
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           9.97e-18
Time:                            14:26:19   Log-Likelihood:                -434.24
No. Observations:                      48   AIC:                             882.5
Df Residuals:                          41   BIC:                             895.6
Df Model:                               6
Covariance Type:                nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                        279.5417    446.865      0.626      0.535    -622.921    1182.004
RendimentoTotal                    0.1315      0.099      1.334      0.190      -0.068       0.331
Salario                            0.2840      0.139      2.048      0.047       0.004       0.564
LimitedeCreditoImediato            0.2410      0.409      0.589      0.559      -0.585       1.067
Escolaridade_Fundamental_Medio  -280.4080    504.571     -0.556      0.581   -1299.409     738.593
Escolaridade_Superior_Pos        559.9498    556.481      1.006      0.320    -563.887    1683.786
GÃªnero_RJ                      -1011.0898    394.413     -2.564      0.014   -1807.623    -214.557
GÃªnero_SP                       1290.6315    484.666      2.663      0.011     311.828    2269.435
RegiÃ£o_F                       -1510.5634    467.696     -3.230      0.002   -2455.094    -566.033
RegiÃ£o_M                        1790.1052    647.038      2.767      0.008     483.386    3096.825
==============================================================================
Omnibus:                       15.771   Durbin-Watson:                   1.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.413
Skew:                          -0.684   Prob(JB):                     1.02e-09
Kurtosis:                       7.340   Cond. No.                     2.58e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.6e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [26]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario	+  LimitedeCreditoImediato+ Escolaridade_Superior_Pos+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.885
Model:                                OLS   Adj. R-squared:                  0.869
Method:                     Least Squares   F-statistic:                     52.78
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           9.97e-18
Time:                            14:27:00   Log-Likelihood:                -434.24
No. Observations:                      48   AIC:                             882.5
Df Residuals:                          41   BIC:                             895.6
Df Model:                               6
Covariance Type:                nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                   139.3377    579.345      0.241      0.811   -1030.673    1309.349
RendimentoTotal               0.1315      0.099      1.334      0.190      -0.068       0.331
Salario                       0.2840      0.139      2.048      0.047       0.004       0.564
LimitedeCreditoImediato       0.2410      0.409      0.589      0.559      -0.585       1.067
Escolaridade_Superior_Pos   840.3578    963.762      0.872      0.388   -1105.999    2786.715
GÃªnero_RJ                 -1081.1918    386.454     -2.798      0.008   -1861.651    -300.732
GÃªnero_SP                  1220.5295    555.961      2.195      0.034      97.744    2343.315
RegiÃ£o_F                  -1580.6654    398.071     -3.971      0.000   -2384.585    -776.745
RegiÃ£o_M                   1720.0031    739.536      2.326      0.025     226.480    3213.526
==============================================================================
Omnibus:                       15.771   Durbin-Watson:                   1.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.413
Skew:                          -0.684   Prob(JB):                     1.02e-09
Kurtosis:                       7.340   Cond. No.                     2.92e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.81e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [30]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario- 1	+  LimitedeCreditoImediato+ Escolaridade_Superior_Pos+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.885
Model:                                OLS   Adj. R-squared:                  0.869
Method:                     Least Squares   F-statistic:                     52.78
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           9.97e-18
Time:                            14:30:12   Log-Likelihood:                -434.24
No. Observations:                      48   AIC:                             882.5
Df Residuals:                          41   BIC:                             895.6
Df Model:                               6
Covariance Type:                nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
RendimentoTotal               0.1315      0.099      1.334      0.190      -0.068       0.331
Salario                       0.2840      0.139      2.048      0.047       0.004       0.564
LimitedeCreditoImediato       0.2410      0.409      0.589      0.559      -0.585       1.067
Escolaridade_Superior_Pos   840.3578    963.762      0.872      0.388   -1105.999    2786.715
GÃªnero_RJ                 -1011.5229    566.749     -1.785      0.082   -2156.096     133.050
GÃªnero_SP                  1290.1984    800.435      1.612      0.115    -326.313    2906.709
RegiÃ£o_F                  -1510.9966    464.720     -3.251      0.002   -2449.517    -572.476
RegiÃ£o_M                   1789.6720    996.429      1.796      0.080    -222.657    3802.001
==============================================================================
Omnibus:                       15.771   Durbin-Watson:                   1.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.413
Skew:                          -0.684   Prob(JB):                     1.02e-09
Kurtosis:                       7.340   Cond. No.                     1.73e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.03e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [31]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario-1	+ Escolaridade_Superior_Pos+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.884
Model:                                OLS   Adj. R-squared:                  0.871
Method:                     Least Squares   F-statistic:                     64.26
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           1.39e-18
Time:                            14:30:18   Log-Likelihood:                -434.44
No. Observations:                      48   AIC:                             880.9
Df Residuals:                          42   BIC:                             892.1
Df Model:                               5
Covariance Type:                nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
RendimentoTotal               0.1210      0.096      1.257      0.216      -0.073       0.315
Salario                       0.2937      0.137      2.149      0.037       0.018       0.569
Escolaridade_Superior_Pos   788.0449    952.173      0.828      0.413   -1133.519    2709.608
GÃªnero_RJ                  -756.1926    362.315     -2.087      0.043   -1487.374     -25.011
GÃªnero_SP                  1609.6887    584.102      2.756      0.009     430.923    2788.455
RegiÃ£o_F                  -1365.9501    391.057     -3.493      0.001   -2155.135    -576.765
RegiÃ£o_M                   2219.4462    673.400      3.296      0.002     860.469    3578.423
==============================================================================
Omnibus:                       18.013   Durbin-Watson:                   1.737
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.309
Skew:                          -0.774   Prob(JB):                     2.66e-12
Kurtosis:                       7.925   Cond. No.                     2.93e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.79e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [32]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario-1	+  LimitedeCreditoImediato+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.883
Model:                                OLS   Adj. R-squared:                  0.869
Method:                     Least Squares   F-statistic:                     63.55
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           1.71e-18
Time:                            14:30:30   Log-Likelihood:                -434.68
No. Observations:                      48   AIC:                             881.4
Df Residuals:                          42   BIC:                             892.6
Df Model:                               5
Covariance Type:                nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
RendimentoTotal             0.1111      0.096      1.164      0.251      -0.082       0.304
Salario                     0.3174      0.133      2.387      0.022       0.049       0.586
LimitedeCreditoImediato     0.2081      0.406      0.512      0.611      -0.612       1.028
GÃªnero_RJ                -973.3266    563.439     -1.727      0.091   -2110.392     163.739
GÃªnero_SP                1547.5988    741.886      2.086      0.043      50.413    3044.785
RegiÃ£o_F                -1613.9103    448.198     -3.601      0.001   -2518.410    -709.411
RegiÃ£o_M                 2188.1824    882.904      2.478      0.017     406.410    3969.954
==============================================================================
Omnibus:                       19.370   Durbin-Watson:                   1.623
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.512
Skew:                          -0.904   Prob(JB):                     2.40e-12
Kurtosis:                       7.847   Cond. No.                     2.79e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.08e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [33]:
function='LimitedoChequeEspecial~RendimentoTotal+Salario-1+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.883
Model:                                OLS   Adj. R-squared:                  0.872
Method:                     Least Squares   F-statistic:                     80.75
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           2.02e-19
Time:                            14:32:09   Log-Likelihood:                -434.83
No. Observations:                      48   AIC:                             879.7
Df Residuals:                          43   BIC:                             889.0
Df Model:                               4
Covariance Type:                nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
RendimentoTotal     0.1031      0.093      1.103      0.276      -0.085       0.291
Salario             0.3239      0.131      2.469      0.018       0.059       0.588
GÃªnero_RJ        -753.0020    360.965     -2.086      0.043   -1480.957     -25.047
GÃªnero_SP        1811.9221    528.588      3.428      0.001     745.924    2877.921
RegiÃ£o_F        -1481.9930    363.717     -4.075      0.000   -2215.498    -748.488
RegiÃ£o_M         2540.9131    548.070      4.636      0.000    1435.624    3646.202
==============================================================================
Omnibus:                       21.294   Durbin-Watson:                   1.615
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               65.346
Skew:                          -0.973   Prob(JB):                     6.46e-15
Kurtosis:                       8.374   Cond. No.                     2.72e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.23e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [35]:
function='LimitedoChequeEspecial~Salario-1+ GÃªnero_RJ+	GÃªnero_SP+	RegiÃ£o_F+	RegiÃ£o_M'
model=smf.ols(formula=function,data=limite).fit()
print(model.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     LimitedoChequeEspecial   R-squared:                       0.879
Model:                                OLS   Adj. R-squared:                  0.871
Method:                     Least Squares   F-statistic:                     106.7
Date:                    Wed, 30 Nov 2022   Prob (F-statistic):           3.24e-20
Time:                            14:33:00   Log-Likelihood:                -435.50
No. Observations:                      48   AIC:                             879.0
Df Residuals:                          44   BIC:                             886.5
Df Model:                               3
Covariance Type:                nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Salario        0.4616      0.041     11.367      0.000       0.380       0.543
GÃªnero_RJ   -762.7325    361.748     -2.108      0.041   -1491.788     -33.677
GÃªnero_SP   1633.0786    504.366      3.238      0.002     616.596    2649.561
RegiÃ£o_F   -1546.3828    359.891     -4.297      0.000   -2271.696    -821.070
RegiÃ£o_M    2416.7289    537.714      4.494      0.000    1333.037    3500.421
==============================================================================
Omnibus:                       11.932   Durbin-Watson:                   1.646
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               29.897
Skew:                          -0.402   Prob(JB):                     3.22e-07
Kurtosis:                       6.782   Cond. No.                     1.76e+20
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.02e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.